### ISSUE TITLE
Beacon crypto key

### ISSUE THREAD

**Issue by tuxmark5** [yellows8/ctr-wlanbeacontool#1]
Hello,
I've been trying to generate the beacon crypto key for some packets I captured for a while, but the method described in http://3dbrew.org/wiki/NWM_Services seems to be incorrect/incomplete.

Is there an example of how to do that properly somewhere?
At least some clarifications would be nice. The section "CTR used for beacon tags crypto" doesn't explicitly mention whether the structure should be sent through MD5 or not (so I've been bruteforcing both methods in hope that one of them works).

Also the wiki mentions "All data here is all-zero except for the MAC address, when the u8 at offset 0x8 in the network-struct is 0.", however the offset 0x8 is not visible when observing captured packets, because the OUI Type 21 contains the network structure only starting from offset 0xC (and therefore everything before 0xC is 0x00).

I'm sorry if this is incorrect place to post such questions, however I'm running out of options.

**Comment by yellows8** [comment]
Paste/whatever your code.

**Comment by tuxmark5** [comment]
This is the packet:
https://dl.dropboxusercontent.com/u/24623852/3DS/aaa.pcap

This is the ruby script:
http://pastebin.com/X8EjAJ8q

**Comment by yellows8** [comment]
I'm not sure what "beacon key" you're talking about, ctr-wlanbeacontool already has code for that. Perhaps you mean the UDS CCMP key?

**Comment by tuxmark5** [comment]
Basically I need the key that lets me decrypt beacon tags.
The OUI Type 24 contains encrypted data that I want to see/generate.

**Comment by yellows8** [comment]
You don't "generate" that, it's from the NWM-module ExeFS:/.code, hence: "The AES key is stored in NWM module itself".

**Comment by tuxmark5** [comment]
How do other 3DSes then decrypt the data that is broadcasted?

**Comment by yellows8** [comment]
Huh?

**Comment by tuxmark5** [comment]
Say we have 2 3DSes. 
The 3DS A broadcasts a UDS Beacon and that beacon has OUI Type 24 section.
According to wiki, the OUI Type 24 has Encrypted data. 
The 3DS B has to somehow decrypt the data that is stored in OUI Type 24 or otherwise there is no point to broadcast that information to begin with.

That or I'm not getting something.

**Comment by yellows8** [comment]
http://3dbrew.org/wiki/NWM_Services#CTR_used_for_beacon_tags_crypto

**Comment by tuxmark5** [comment]
I probably should explain what I'm trying to achieve here. That might make some things clearer.
My goal is to spoof 3ds communication. In other words, I want my PC to pretend to be another 3ds and to emulate 3ds communication in such way that another 3ds would 'believe' that it is communicating with a real 3ds.

I've already constructed ruby script that assembles all low level frames and broadcasts them through a raw wireless interface. However right now my 3ds isn't seeing any 'passerbys'. The reason why it's not working yet might be because I'm rebroadcasting previously captured packets with slight modifications. However I've not yet figured out how to properly construct OUI Type 24 tag, because it's encrypted.

And yes, I've been using the structure described in
http://3dbrew.org/wiki/NWM_Services#CTR_used_for_beacon_tags_crypto
to generate the key that I then store in ~/.3ds/nwmbeacon_key, but ctr-wlanbeacontool claims that hash is invalid and therefore my key must be invalid too.

**Comment by yellows8** [comment]
"generate the key " Ugh, can't you read? https://github.com/yellows8/ctr-wlanbeacontool/issues/1#issuecomment-66339348

**Comment by tuxmark5** [comment]
So the key is shared then across all 3DSes?

**Comment by yellows8** [comment]
Obviously.

**Comment by tuxmark5** [comment]
Has it been dumped yet?

**Comment by yellows8** [comment]
It's not public, if you want it you have to extract it yourself.

**Comment by tuxmark5** [comment]
Oh. That complicates things then.

**Comment by yellows8** [comment]
"assembles all low level frames" <- What does that do which ctr-wlanbeacontool doesn't already do?

**Comment by tuxmark5** [comment]
I found the tool after I've written a copy-cat script that rebroadcasts the modified frames I've captured before.

**Comment by tuxmark5** [comment]
Also, would there be any 'other' way I could obtain the said key?
I don't really have a 3ds with older firmware and thus I can't really jailbreak it.

**Comment by yellows8** [comment]
I don't really want to share that, so uh...

**Comment by tuxmark5** [comment]
Maybe you know someone who would?
After all, the key is in my 3ds too, so I wouldn't be breaking any rules by seeking it out.

**Comment by tuxmark5** [comment]
Do you use IRC or something similar? Github issue forum is not the most efficient method to discuss this.

**Comment by yellows8** [comment]
EFNet #3dsdev
