### ISSUE TITLE
Compile errors with make

### ISSUE THREAD

**Issue by itsugawakun** [yellows8/ctr-wlanbeacontool#4]
Hi i've been trying to compile the program and got an error with openssl. Already tried to reboot, remove, reinstall using vm so on and so forth. 

> ctr-wlanbeacontool-master/source/ctr-wlanbeacontool.c:5:10: fatal error: 
>       'openssl/md5.h' file not found
> # include "<"openssl/md5.h">"
> 
> .             ^
> 1 error generated.
> make[1]: **\* [ctr-wlanbeacontool.o] Error 1
> make: **\* [build_nix] Error 2

I have os x El Capitan and vm is Ubuntu 14

if you need more info please let me know

thanks in advance

**Comment by yellows8** [comment]
{failed to find library during building} Is not really specific to {insert app using library}.

**Comment by itsugawakun** [comment]
so i looked around and a simple `brew link --force openssl` works for the fix.
