### ISSUE TITLE
File not generated at the end (Stacktrace included)

### ISSUE THREAD

**Issue by pascuaalvi** [yellows8/ctr-wlanbeacontool#6]
I called `make clean` and `make` on the ctr-wlanbeacontool-master directory.
This is the result:

--- start stacktrace ----

ctr-wlanbeacontool.c
gcc -MMD -MP -MF /home/pascuaalvi/hx/ctr-wlanbeacontool-master/build_nix/ctr-wlanbeacontool.d -Wall -O2 -I/home/pascuaalvi/hx/ctr-wlanbeacontool-master/include   -I/home/pascuaalvi/hx/ctr-wlanbeacontool-master/build_nix -c /home/pascuaalvi/hx/ctr-wlanbeacontool-master/source/ctr-wlanbeacontool.c -o ctr-wlanbeacontool.o
In file included from /usr/include/pcap/pcap.h:45:0,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /usr/include/pcap/pcap.h:45,
                 from /home/pascuaalvi/hx/ctr-wlanbeacontool-master/source/ctr-wlanbeacontool.c:4:
/usr/include/pcap/pcap.h:45:23: error: #include nested too deeply
/home/pascuaalvi/hx/ctr-wlanbeacontool-master/source/ctr-wlanbeacontool.c:353:129: warning: ‘struct pcap_pkthdr’ declared inside parameter list
 int generate_beacon(unsigned char _inframebuf, unsigned char *framebuf, unsigned int framestart, unsigned int framesize, struct pcap_pkthdr *pkthdr, unsigned int has_fcs)
                                                                                                                                 ^
/home/pascuaalvi/hx/ctr-wlanbeacontool-master/source/ctr-wlanbeacontool.c:353:129: warning: its scope is only this definition or declaration, which is probably not what you want
/home/pascuaalvi/hx/ctr-wlanbeacontool-master/source/ctr-wlanbeacontool.c: In function ‘generate_beacon’:
/home/pascuaalvi/hx/ctr-wlanbeacontool-master/source/ctr-wlanbeacontool.c:574:8: error: dereferencing pointer to incomplete type ‘struct pcap_pkthdr’
  pkthdr->caplen = framesize;
        ^
/home/pascuaalvi/hx/ctr-wlanbeacontool-master/source/ctr-wlanbeacontool.c: In function ‘main’:
/home/pascuaalvi/hx/ctr-wlanbeacontool-master/source/ctr-wlanbeacontool.c:586:2: error: unknown type name ‘pcap_dumper_t’
  pcap_dumper_t *pcap_dumper;
  ^
/home/pascuaalvi/hx/ctr-wlanbeacontool-master/source/ctr-wlanbeacontool.c:587:2: error: unknown type name ‘pcap_t’
  pcap_t *pcap;
  ^
/home/pascuaalvi/hx/ctr-wlanbeacontool-master/source/ctr-wlanbeacontool.c:589:21: error: storage size of ‘pkthdr’ isn’t known
  struct pcap_pkthdr pkthdr;
                     ^
/home/pascuaalvi/hx/ctr-wlanbeacontool-master/source/ctr-wlanbeacontool.c:596:14: error: ‘PCAP_ERRBUF_SIZE’ undeclared (first use in this function)
  char errbuf[PCAP_ERRBUF_SIZE];
              ^
/home/pascuaalvi/hx/ctr-wlanbeacontool-master/source/ctr-wlanbeacontool.c:596:14: note: each undeclared identifier is reported only once for each function it appears in
/home/pascuaalvi/hx/ctr-wlanbeacontool-master/source/ctr-wlanbeacontool.c:691:9: warning: implicit declaration of function ‘pcap_open_offline’ [-Wimplicit-function-declaration]
  pcap = pcap_open_offline(inpath, errbuf);
         ^
/home/pascuaalvi/hx/ctr-wlanbeacontool-master/source/ctr-wlanbeacontool.c:694:3: warning: implicit declaration of function ‘pcap_perror’ [-Wimplicit-function-declaration]
   pcap_perror(pcap, "pcap_open_offline() failed: ");
   ^
/home/pascuaalvi/hx/ctr-wlanbeacontool-master/source/ctr-wlanbeacontool.c:699:13: warning: implicit declaration of function ‘pcap_datalink’ [-Wimplicit-function-declaration]
  linktype = pcap_datalink(pcap);
             ^
/home/pascuaalvi/hx/ctr-wlanbeacontool-master/source/ctr-wlanbeacontool.c:700:12: warning: implicit declaration of function ‘pcap_snapshot’ [-Wimplicit-function-declaration]
  snaplen = pcap_snapshot(pcap);
            ^
/home/pascuaalvi/hx/ctr-wlanbeacontool-master/source/ctr-wlanbeacontool.c:704:9: warning: implicit declaration of function ‘pcap_next_ex’ [-Wimplicit-function-declaration]
   ret = pcap_next_ex(pcap, &pkt_header, &pkt_data);
         ^
/home/pascuaalvi/hx/ctr-wlanbeacontool-master/source/ctr-wlanbeacontool.c:710:4: warning: implicit declaration of function ‘pcap_close’ [-Wimplicit-function-declaration]
    pcap_close(pcap);
    ^
/home/pascuaalvi/hx/ctr-wlanbeacontool-master/source/ctr-wlanbeacontool.c:715:25: error: dereferencing pointer to incomplete type ‘struct pcap_pkthdr’
   framesize = pkt_header->caplen;
                         ^
/home/pascuaalvi/hx/ctr-wlanbeacontool-master/source/ctr-wlanbeacontool.c:718:16: error: ‘DLT_IEEE802_11_RADIO’ undeclared (first use in this function)
   if(linktype==DLT_IEEE802_11_RADIO)framestart+= *((unsigned short_)&pkt_data[2]);
                ^
/home/pascuaalvi/hx/ctr-wlanbeacontool-master/source/ctr-wlanbeacontool.c:745:40: error: invalid application of ‘sizeof’ to incomplete type ‘struct pcap_pkthdr’
     memcpy(&pkthdr, pkt_header, sizeof(struct pcap_pkthdr));
                                        ^
/home/pascuaalvi/hx/ctr-wlanbeacontool-master/source/ctr-wlanbeacontool.c:805:9: warning: implicit declaration of function ‘pcap_open_dead’ [-Wimplicit-function-declaration]
  pcap = pcap_open_dead(linktype, snaplen);
         ^
/home/pascuaalvi/hx/ctr-wlanbeacontool-master/source/ctr-wlanbeacontool.c:805:7: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  pcap = pcap_open_dead(linktype, snaplen);
       ^
/home/pascuaalvi/hx/ctr-wlanbeacontool-master/source/ctr-wlanbeacontool.c:806:16: warning: implicit declaration of function ‘pcap_dump_open’ [-Wimplicit-function-declaration]
  pcap_dumper = pcap_dump_open(pcap, outpath);
                ^
/home/pascuaalvi/hx/ctr-wlanbeacontool-master/source/ctr-wlanbeacontool.c:806:14: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  pcap_dumper = pcap_dump_open(pcap, outpath);
              ^
/home/pascuaalvi/hx/ctr-wlanbeacontool-master/source/ctr-wlanbeacontool.c:815:2: warning: implicit declaration of function ‘pcap_dump’ [-Wimplicit-function-declaration]
  pcap_dump((u_char_)pcap_dumper, &pkthdr, outframebuf);
  ^
/home/pascuaalvi/hx/ctr-wlanbeacontool-master/source/ctr-wlanbeacontool.c:817:2: warning: implicit declaration of function ‘pcap_dump_close’ [-Wimplicit-function-declaration]
  pcap_dump_close(pcap_dumper);
  ^
/home/pascuaalvi/hx/ctr-wlanbeacontool-master/source/ctr-wlanbeacontool.c:596:7: warning: unused variable ‘errbuf’ [-Wunused-variable]
  char errbuf[PCAP_ERRBUF_SIZE];
       ^
/home/pascuaalvi/hx/ctr-wlanbeacontool-master/source/ctr-wlanbeacontool.c:589:21: warning: unused variable ‘pkthdr’ [-Wunused-variable]
  struct pcap_pkthdr pkthdr;
                     ^
make[1]: *_\* [/home/pascuaalvi/hx/ctr-wlanbeacontool-master/Makefile:31: ctr-wlanbeacontool.o] Error 1
make: **\* [Makefile:129: build_nix] Error 2

--- end stacktrace ----

The file is not being generated at the end of this, might you know why?
- **I've installed both pcap and openssl**
- **This was done in Cygwin.**

**Comment by yellows8** [comment]
Well libpcap is clearly not installed properly...

**Comment by pascuaalvi** [comment]
Thanks for that. Just did the entire thing again in Linux terminal and it worked.

Cygwin is just a pig....

**Comment by shakkar23** [comment]
i dont have a linux but stickerhax worked for me but not smash (not yet)
